### ISSUE TITLE
front end stuck

### ISSUE THREAD

**Issue by eelxpeng** [mckaywrigley/chatbot-ui-lite#2]
I tried to start the sever in local using npm run dev, but somehow the front end always stuck at https://github.com/mckaywrigley/chatbot-ui/blob/main/pages/index.tsx#L24. I tried to add logging, and it just never return in the fetch of `/api/chat`. Do you know why?

**Comment by mckaywrigley** [comment]
Are you adding your api key to a .env.local file?
